spring.application.name=apiVuelos
spring.datasource.url=jdbc:mysql://localhost:3306/vuelos_persistence
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9000

# Abrir la UI en el navegador al iniciar (true/false)
app.ui.open-browser=true
